# Use root/example as user/password credentials

version: '3.6'

services:
  db:
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: password1234 
      MYSQL_USER: user 
      MYSQL_PASSWORD: password 
      MYSQL_DATABASE: jointproject
      
  web:
    image: danic96/jointproject:arm-test
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      
    
