version: '3'
services:
  db:
    image: postgres
    deploy:
        replicas: 1
  web:
    image: danic96/jointproject
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
      - webnet
    depends_on:
      - db
networks:
  webnet:
