# Use root/example as user/password credentials

version: '3.6'

services:
  db:
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: password1234 
      MYSQL_USER: user 
      MYSQL_PASSWORD: password 
      MYSQL_DATABASE: jointproject
